const DEFAULT_SETTINGS={companyName:"ViajaPro",currency:"CLP",contactPhone:"+56 9 1234 5678",contactEmail:"contacto@viajapro.cl",paymentMethods:["Webpay","Mercado Pago","Transferencia","Efectivo"],emailEndpoint:""};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),read=(k,d=[])=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)),write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
if(!localStorage.getItem("vp_trips"))write("vp_trips",[]);if(!localStorage.getItem("vp_events"))write("vp_events",[]);if(!localStorage.getItem("vp_bookings"))write("vp_bookings",[]);if(!localStorage.getItem("vp_settings"))write("vp_settings",DEFAULT_SETTINGS);
const getTrips=()=>read("vp_trips"),getEvents=()=>read("vp_events"),getBookings=()=>read("vp_bookings"),getSettings=()=>({...DEFAULT_SETTINGS,...read("vp_settings",DEFAULT_SETTINGS)});
const money=v=>new Intl.NumberFormat("es-CL",{style:"currency",currency:getSettings().currency||"CLP",maximumFractionDigits:0}).format(v),fmtDate=d=>new Date(d+"T12:00:00").toLocaleDateString("es-CL"),esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function toast(m){const t=$("#toast");t.textContent=m;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),2600);}function showApp(){$("#loginScreen").classList.add("hidden");$("#adminApp").classList.remove("hidden");renderAll();initScanner();}
$("#loginForm").onsubmit=e=>{e.preventDefault();if($("#adminUser").value==="admin"&&$("#adminPassword").value==="1234"){sessionStorage.setItem("vp_admin","1");showApp();}else toast("Usuario o contraseña incorrectos");};if(sessionStorage.getItem("vp_admin")==="1")showApp();$("#logoutBtn").onclick=()=>{sessionStorage.removeItem("vp_admin");location.reload();};
const meta={dashboard:["Resumen general","Controla viajes, eventos, pagos y accesos."],trips:["Viajes","Administra destinos, fechas y asientos."],events:["Eventos","Administra eventos, lugares y entradas."],bookings:["Compras","Modifica pasajes, entradas y códigos QR."],payments:["Pagos","Controla medios y estados de pago."],scanner:["Lector QR","Valida y registra entradas o pasajes."],settings:["Ajustes","Configura empresa, pagos y correos."],restore:["Restaurar sistema","Respalda o recupera todos los datos."]};
$$('.nav-item').forEach(b=>b.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.admin-view').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.view+'View').classList.add('active');$('#viewTitle').textContent=meta[b.dataset.view][0];$('#viewSubtitle').textContent=meta[b.dataset.view][1];$('#sidebar').classList.remove('open');});$('#sidebarBtn').onclick=()=>$('#sidebar').classList.toggle('open');
function soldTrip(id){return getBookings().filter(b=>b.type==='trip'&&b.itemId===id&&b.status!=='Cancelada').reduce((n,b)=>n+(b.seats?.length||0),0);}function soldEvent(id){return getBookings().filter(b=>b.type==='event'&&b.itemId===id&&b.status!=='Cancelada').reduce((n,b)=>n+(b.quantity||1),0);}function itemName(b){const x=b.type==='trip'?getTrips().find(t=>t.id===b.itemId):getEvents().find(e=>e.id===b.itemId);return b.type==='trip'?(x?`${x.origin} → ${x.destination}`:'Viaje eliminado'):(x?.name||'Evento eliminado');}function statusClass(s){return s==='Activo'||s==='Pagado'?'active':s==='Pausado'||s==='Pendiente'?'paused':'finished';}
function bookingPeople(b){return b.attendees?.length?b.attendees:[{name:b.passenger,document:b.document,seat:(b.seats||[])[0],ticket:1}];}function bookingPeopleHtml(b){return bookingPeople(b).map(a=>`${esc(a.name)} · ${b.type==='trip'?`Asiento ${a.seat}`:`Entrada ${a.ticket}`}`).join('<br>');}
function renderAll(){renderStats();renderTrips();renderEvents();renderBookings($('#bookingSearch')?.value||'');renderPayments($('#paymentFilter')?.value||'');loadSettings();}
function renderStats(){const b=getBookings();$('#statTrips').textContent=getTrips().filter(x=>x.status==='Activo').length;$('#statEvents').textContent=getEvents().filter(x=>x.status==='Activo').length;$('#statBookings').textContent=b.length;$('#statRevenue').textContent=money(b.filter(x=>x.paymentStatus==='Pagado'&&x.status!=='Cancelada').reduce((s,x)=>s+x.total,0));$('#dashboardPurchases').innerHTML=b.slice().reverse().slice(0,8).map(x=>`<tr><td><strong>${esc(x.code)}</strong></td><td>${x.type==='trip'?'Pasaje':'Entrada'}</td><td>${esc(x.passenger)}</td><td><span class="status ${statusClass(x.paymentStatus)}">${esc(x.paymentStatus)}</span></td><td>${money(x.total)}</td><td>${x.checkedIn?'✓ Registrada':'Pendiente'}</td></tr>`).join('')||'<tr><td colspan="6">No hay compras.</td></tr>';}
function renderTrips(){const list=getTrips().sort((a,b)=>a.date.localeCompare(b.date));$('#tripsTable').innerHTML=list.map(t=>`<tr><td><strong>${esc(t.destination)}</strong></td><td>${esc(t.origin)}</td><td>${fmtDate(t.date)}<br><small>${esc(t.time)}</small></td><td>${money(t.price)}</td><td>${soldTrip(t.id)} vendidos / ${t.seats}</td><td><span class="status ${statusClass(t.status)}">${t.status}</span></td><td><button class="action-btn" onclick="editTrip('${t.id}')">Editar</button><button class="action-btn delete" onclick="deleteTrip('${t.id}')">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="7">No hay viajes.</td></tr>';}
function renderEvents(){const list=getEvents().sort((a,b)=>a.date.localeCompare(b.date));$('#eventsTable').innerHTML=list.map(e=>`<tr><td><strong>${esc(e.name)}</strong></td><td>${esc(e.venue)}</td><td>${fmtDate(e.date)}<br><small>${esc(e.time)}</small></td><td>${money(e.price)}</td><td>${soldEvent(e.id)} vendidas / ${e.capacity}</td><td><span class="status ${statusClass(e.status)}">${e.status}</span></td><td><button class="action-btn" onclick="editEvent('${e.id}')">Editar</button><button class="action-btn delete" onclick="deleteEvent('${e.id}')">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="7">No hay eventos.</td></tr>';}
function renderBookings(q=''){q=q.toLowerCase();const list=getBookings().filter(b=>!q||b.code.toLowerCase().includes(q)||b.passenger.toLowerCase().includes(q)||bookingPeople(b).some(a=>a.name.toLowerCase().includes(q)));$('#bookingsTable').innerHTML=list.map(b=>`<tr><td><strong>${esc(b.code)}</strong><br><small>${b.type==='trip'?'Pasaje':'Entrada'}</small></td><td>${bookingPeopleHtml(b)}<br><small>${esc(b.email)}</small></td><td>${esc(itemName(b))}</td><td>${b.type==='trip'?(b.seats||[]).join(', '):b.quantity}</td><td>${money(b.total)}</td><td><span class="status ${b.checkedIn?'finished':'confirmed'}">${b.checkedIn?'✓ Registrada':esc(b.status)}</span></td><td><button class="action-btn" onclick="openBookingEdit('${b.id}')">Modificar</button><button class="action-btn" onclick="validateById('${b.id}')">Validar</button><button class="action-btn delete" onclick="deleteBooking('${b.id}')">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="7">No hay compras.</td></tr>';}
function renderPayments(filter=''){const list=getBookings().filter(b=>!filter||b.paymentStatus===filter);$('#paymentsTable').innerHTML=list.map(b=>`<tr><td><strong>${esc(b.code)}</strong></td><td>${esc(b.passenger)}</td><td>${esc(b.paymentMethod)}</td><td><span class="status ${statusClass(b.paymentStatus)}">${esc(b.paymentStatus)}</span></td><td>${money(b.total)}</td><td>${new Date(b.createdAt).toLocaleDateString('es-CL')}</td><td><select class="inline-select" onchange="changePayment('${b.id}',this.value)"><option ${b.paymentStatus==='Pagado'?'selected':''}>Pagado</option><option ${b.paymentStatus==='Pendiente'?'selected':''}>Pendiente</option><option ${b.paymentStatus==='Reembolsado'?'selected':''}>Reembolsado</option></select></td></tr>`).join('')||'<tr><td colspan="7">No hay pagos.</td></tr>';}
$('#bookingSearch').oninput=e=>renderBookings(e.target.value);$('#paymentFilter').onchange=e=>renderPayments(e.target.value);window.changePayment=(id,v)=>{const l=getBookings(),i=l.findIndex(x=>x.id===id);if(i>=0){l[i].paymentStatus=v;write('vp_bookings',l);renderAll();toast('Estado de pago actualizado');}};
function openTrip(t=null){$('#tripForm').reset();$('#tripId').value=t?.id||'';$('#tripModalTitle').textContent=t?'Editar viaje':'Nuevo viaje';if(t){$('#tripDestination').value=t.destination;$('#tripOrigin').value=t.origin;$('#tripDate').value=t.date;$('#tripTime').value=t.time;$('#tripPrice').value=t.price;$('#tripSeats').value=t.seats;$('#tripImage').value=t.image||'';$('#tripDescription').value=t.description||'';$('#tripStatus').value=t.status;}$('#tripModal').classList.remove('hidden');}$$('[data-open-trip-form]').forEach(b=>b.onclick=()=>openTrip());$$('[data-close-trip-modal]').forEach(b=>b.onclick=()=>$('#tripModal').classList.add('hidden'));window.editTrip=id=>openTrip(getTrips().find(x=>x.id===id));window.deleteTrip=id=>{if(getBookings().some(b=>b.itemId===id&&b.type==='trip'))return toast('No se puede eliminar: tiene compras');if(confirm('¿Eliminar viaje?')){write('vp_trips',getTrips().filter(x=>x.id!==id));renderAll();}};$('#tripForm').onsubmit=e=>{e.preventDefault();const l=getTrips(),id=$('#tripId').value||'t'+Date.now(),x={id,destination:$('#tripDestination').value.trim(),origin:$('#tripOrigin').value.trim(),date:$('#tripDate').value,time:$('#tripTime').value,price:+$('#tripPrice').value,seats:+$('#tripSeats').value,image:$('#tripImage').value.trim(),description:$('#tripDescription').value.trim(),status:$('#tripStatus').value};if(x.seats<soldTrip(id))return toast('No puedes reducir bajo lo ya vendido');const i=l.findIndex(v=>v.id===id);i>=0?l[i]=x:l.push(x);write('vp_trips',l);$('#tripModal').classList.add('hidden');renderAll();toast('Viaje guardado');};
function openEvent(x=null){$('#eventForm').reset();$('#eventId').value=x?.id||'';$('#eventModalTitle').textContent=x?'Editar evento':'Nuevo evento';if(x){$('#eventName').value=x.name;$('#eventVenue').value=x.venue;$('#eventDate').value=x.date;$('#eventTime').value=x.time;$('#eventPrice').value=x.price;$('#eventCapacity').value=x.capacity;$('#eventImage').value=x.image||'';$('#eventDescription').value=x.description||'';$('#eventStatus').value=x.status;}$('#eventModal').classList.remove('hidden');}$$('[data-open-event-form]').forEach(b=>b.onclick=()=>openEvent());$$('[data-close-event-modal]').forEach(b=>b.onclick=()=>$('#eventModal').classList.add('hidden'));window.editEvent=id=>openEvent(getEvents().find(x=>x.id===id));window.deleteEvent=id=>{if(getBookings().some(b=>b.itemId===id&&b.type==='event'))return toast('No se puede eliminar: tiene compras');if(confirm('¿Eliminar evento?')){write('vp_events',getEvents().filter(x=>x.id!==id));renderAll();}};$('#eventForm').onsubmit=e=>{e.preventDefault();const l=getEvents(),id=$('#eventId').value||'e'+Date.now(),x={id,name:$('#eventName').value.trim(),venue:$('#eventVenue').value.trim(),date:$('#eventDate').value,time:$('#eventTime').value,price:+$('#eventPrice').value,capacity:+$('#eventCapacity').value,image:$('#eventImage').value.trim(),description:$('#eventDescription').value.trim(),status:$('#eventStatus').value};if(x.capacity<soldEvent(id))return toast('No puedes reducir bajo lo vendido');const i=l.findIndex(v=>v.id===id);i>=0?l[i]=x:l.push(x);write('vp_events',l);$('#eventModal').classList.add('hidden');renderAll();toast('Evento guardado');};
window.openBookingEdit=id=>{const b=getBookings().find(x=>x.id===id);if(!b)return;$('#editBookingId').value=id;$('#editPassenger').value=b.passenger;$('#editEmail').value=b.email;$('#editStatus').value=b.status;$('#editPaymentStatus').value=b.paymentStatus;$('#editCancelReason').value=b.cancelReason||'';$('#editRefundAmount').value=b.refundAmount??b.total;$('#editRefundMethod').value=b.refundMethod||'';$('#bookingModal').classList.remove('hidden');};$$('[data-close-booking-modal]').forEach(b=>b.onclick=()=>$('#bookingModal').classList.add('hidden'));$('#bookingEditForm').onsubmit=e=>{e.preventDefault();const l=getBookings(),i=l.findIndex(x=>x.id===$('#editBookingId').value);if(i>=0){l[i].passenger=$('#editPassenger').value.trim();l[i].email=$('#editEmail').value.trim();l[i].status=$('#editStatus').value;l[i].paymentStatus=$('#editPaymentStatus').value;l[i].cancelReason=$('#editCancelReason').value.trim();l[i].refundAmount=+$('#editRefundAmount').value||0;l[i].refundMethod=$('#editRefundMethod').value;if(l[i].status==='Cancelada'&&!l[i].cancelledAt)l[i].cancelledAt=new Date().toISOString();write('vp_bookings',l);}$('#bookingModal').classList.add('hidden');renderAll();toast('Compra modificada');};
async function sendCancellationEmail(b){const st=getSettings(),subject=`Cancelación y devolución ${b.code}`,payload={to:b.email,subject,purchase:b,cancellation:true};if(st.emailEndpoint){try{const r=await fetch(st.emailEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(r.ok){toast('Correo de cancelación enviado');return;}}catch{}}const body=encodeURIComponent(`Hola ${b.passenger},\n\nTu ${b.type==='trip'?'viaje':'evento'} fue cancelado.\nCódigo: ${b.code}\nMotivo: ${b.cancelReason||'No informado'}\nMonto de devolución: ${money(b.refundAmount||0)}\nMétodo: ${b.refundMethod||'No informado'}\nEstado del pago: ${b.paymentStatus}\n\nPara consultas escribe a ${st.contactEmail}.`);location.href=`mailto:${encodeURIComponent(b.email)}?subject=${encodeURIComponent(subject)}&body=${body}`;}
$('#cancelAndRefundBtn').onclick=()=>{const id=$('#editBookingId').value,l=getBookings(),i=l.findIndex(x=>x.id===id);if(i<0)return;const reason=$('#editCancelReason').value.trim(),method=$('#editRefundMethod').value,amount=+$('#editRefundAmount').value||0;if(!reason)return toast('Ingresa el motivo de cancelación');if(!method)return toast('Selecciona el método de devolución');if(!confirm('¿Cancelar esta compra y anular su código QR?'))return;l[i].status='Cancelada';l[i].paymentStatus='Reembolsado';l[i].cancelReason=reason;l[i].refundAmount=amount;l[i].refundMethod=method;l[i].cancelledAt=new Date().toISOString();l[i].refundedAt=new Date().toISOString();l[i].checkedIn=false;l[i].checkedInAt=null;write('vp_bookings',l);$('#bookingModal').classList.add('hidden');renderAll();sendCancellationEmail(l[i]);toast('Compra cancelada y devolución registrada');};
function parseQr(raw){try{const o=JSON.parse(raw);return {purchaseCode:o.code||'',personCode:o.personCode||o.attendeeCode||o.code||''}}catch{const x=String(raw||'').trim();return {purchaseCode:x,personCode:x}}}
function ensureBookingPeople(b){if(!b.attendees?.length)b.attendees=bookingPeople(b).map((a,i)=>({...a,qrCode:`${b.code}-${String(i+1).padStart(2,'0')}`,checkedIn:!!b.checkedIn,checkedInAt:b.checkedInAt||null,checkedInBy:b.checkedInBy||null}));return b.attendees}
let adminScanLocked=false,adminFeedbackTimer=null;
function showAdminScanFeedback(ok,title,detail=''){let box=document.querySelector('#qrAutoFeedback');if(!box){box=document.createElement('div');box.id='qrAutoFeedback';box.className='qr-auto-feedback hidden';document.body.appendChild(box)}box.className=`qr-auto-feedback ${ok?'ok':'bad'}`;box.innerHTML=`<div class="qr-auto-symbol">${ok?'✓':'✕'}</div><h2>${esc(title)}</h2>${detail?`<p>${esc(detail)}</p>`:''}`;clearTimeout(adminFeedbackTimer);adminFeedbackTimer=setTimeout(()=>{box.classList.add('hidden');adminScanLocked=false;document.querySelector('#scanResult').innerHTML='<div class="empty-icon">▣</div><p>Escanea un código.</p>'},2000)}
function validateCode(raw){if(adminScanLocked)return;adminScanLocked=true;const parsed=parseQr(raw),purchase=parsed.purchaseCode.toUpperCase(),person=parsed.personCode.toUpperCase(),l=getBookings();let i=l.findIndex(x=>x.code.toUpperCase()===purchase||ensureBookingPeople(x).some(a=>(a.qrCode||'').toUpperCase()===person)),out=$('#scanResult');if(i<0){out.innerHTML='<div class="scan-bad">✕</div><h3>QR no válido</h3><p>No existe una compra con este código.</p>';showAdminScanFeedback(false,'QR no válido','Código inexistente');return}const b=l[i],kind=b.type==='trip'?'Pasaje':'Entrada',ps=ensureBookingPeople(b);let ai=ps.findIndex(a=>(a.qrCode||'').toUpperCase()===person);if(ai<0&&person===b.code.toUpperCase())ai=0;if(ai<0){showAdminScanFeedback(false,'QR no válido','No corresponde a una persona registrada');return}const a=ps[ai];if(b.status==='Cancelada'||b.paymentStatus==='Reembolsado'){showAdminScanFeedback(false,'QR no válido',`${kind} cancelado o reembolsado`);return}if(a.checkedIn){out.innerHTML=`<div class="scan-bad">✕</div><h3>Ya registrado</h3><p>${esc(a.name)} ingresó el ${new Date(a.checkedInAt).toLocaleString('es-CL')}.</p>`;showAdminScanFeedback(false,'QR ya utilizado',`${a.name} ya fue registrado`);return}const now=new Date().toISOString();ps[ai]={...a,checkedIn:true,checkedInAt:now,checkedInBy:'administrador'};b.attendees=ps;b.checkedIn=ps.every(x=>x.checkedIn);b.checkedInAt=b.checkedIn?now:null;b.checkedInBy=b.checkedIn?'administrador':null;write('vp_bookings',l);out.innerHTML=`<div class="scan-good">✓</div><h3>${kind} registrado</h3><p><strong>${esc(a.name)}</strong><br>${b.type==='trip'?`Asiento ${a.seat}`:`Entrada ${a.ticket}`}<br>${esc(itemName(b))}</p>`;renderAll();showAdminScanFeedback(true,`${kind} válido`,a.name)}
window.validateById=id=>{const b=getBookings().find(x=>x.id===id);document.querySelector('[data-view="scanner"]').click();if(b){const a=ensureBookingPeople(b)[0];validateCode(a?.qrCode||b.code);}};
$('#validateQrBtn').onclick=()=>validateCode($('#manualQr').value);
let scannerStarted=false;function initScanner(){if(scannerStarted||!window.Html5QrcodeScanner)return;scannerStarted=true;try{const sc=new Html5QrcodeScanner('qrReader',{fps:10,qrbox:{width:230,height:230}},false);sc.render(text=>{validateCode(text);},()=>{});}catch{scannerStarted=false;}}
function loadSettings(){const s=getSettings();$('#companyName').value=s.companyName||'';$('#currency').value=s.currency||'CLP';$('#contactPhone').value=s.contactPhone||'';$('#contactEmail').value=s.contactEmail||'';$('#emailEndpoint').value=s.emailEndpoint||'';$$('input[name="payMethod"]').forEach(c=>c.checked=(s.paymentMethods||[]).includes(c.value));}$('#settingsForm').onsubmit=e=>{e.preventDefault();const methods=[...$$('input[name="payMethod"]:checked')].map(x=>x.value);if(!methods.length)return toast('Selecciona al menos un medio de pago');write('vp_settings',{companyName:$('#companyName').value.trim(),currency:$('#currency').value,contactPhone:$('#contactPhone').value.trim(),contactEmail:$('#contactEmail').value.trim(),emailEndpoint:$('#emailEndpoint').value.trim(),paymentMethods:methods});renderAll();toast('Ajustes guardados');};


window.deleteBooking=id=>{const b=getBookings().find(x=>x.id===id);if(!b)return;if(!confirm(`¿Eliminar definitivamente la compra ${b.code}? Esta acción también elimina su QR y registro.`))return;write('vp_bookings',getBookings().filter(x=>x.id!==id));renderAll();toast('Compra eliminada');};

function fullBackup(){return {app:'ViajaPro',version:3,exportedAt:new Date().toISOString(),trips:getTrips(),events:getEvents(),bookings:getBookings(),settings:getSettings()};}
if(!localStorage.getItem('vp_factory_snapshot'))localStorage.setItem('vp_factory_snapshot',JSON.stringify(fullBackup()));
$('#exportBackupBtn').onclick=()=>{const blob=new Blob([JSON.stringify(fullBackup(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ViajaPro_respaldo_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Respaldo descargado');};
$('#importBackupBtn').onclick=()=>{const f=$('#importBackupFile').files[0];if(!f)return toast('Selecciona un archivo JSON');const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.trips)||!Array.isArray(d.events)||!Array.isArray(d.bookings)||!d.settings)throw new Error();if(!confirm('¿Reemplazar todos los datos por este respaldo?'))return;write('vp_trips',d.trips);write('vp_events',d.events);write('vp_bookings',d.bookings);write('vp_settings',d.settings);renderAll();toast('Sistema restaurado desde respaldo');}catch{toast('El archivo no es un respaldo válido');}};r.readAsText(f);};
$('#factoryRestoreBtn').onclick=()=>{if(!confirm('¿Restaurar el sistema inicial? Se perderán los cambios actuales.'))return;try{const d=JSON.parse(localStorage.getItem('vp_factory_snapshot'));write('vp_trips',d.trips||[]);write('vp_events',d.events||[]);write('vp_bookings',d.bookings||[]);write('vp_settings',d.settings||DEFAULT_SETTINGS);renderAll();toast('Sistema restaurado');}catch{toast('No se pudo restaurar el sistema');}};
