const DEFAULT_TRIPS=[
{id:"t1",destination:"Viña del Mar",origin:"Santiago",date:"2026-08-02",time:"08:30",price:18500,seats:40,status:"Activo",image:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80",description:"Viaje directo con aire acondicionado y equipaje incluido."},
{id:"t2",destination:"Valparaíso",origin:"Santiago",date:"2026-08-09",time:"07:45",price:17000,seats:36,status:"Activo",image:"https://images.unsplash.com/photo-1544986581-efac024faf62?auto=format&fit=crop&w=1000&q=80",description:"Salida de fin de semana para disfrutar la ciudad puerto."},
{id:"t3",destination:"Pucón",origin:"Santiago",date:"2026-08-16",time:"22:00",price:45900,seats:44,status:"Activo",image:"https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1000&q=80",description:"Viaje nocturno cómodo y seguro hacia el sur de Chile."}
];
const DEFAULT_EVENTS=[
{id:"e1",name:"Festival de Música Santiago",venue:"Parque O'Higgins",date:"2026-08-22",time:"18:00",price:25000,capacity:500,status:"Activo",image:"https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1000&q=80",description:"Música en vivo, gastronomía y una experiencia para toda la familia."},
{id:"e2",name:"Noche de Comedia",venue:"Teatro Centro",date:"2026-09-05",time:"20:30",price:16000,capacity:180,status:"Activo",image:"https://images.unsplash.com/photo-1527224857830-43a7acc85260?auto=format&fit=crop&w=1000&q=80",description:"Una noche especial con destacados comediantes nacionales."}
];
const DEFAULT_SETTINGS={companyName:"ViajaPro",currency:"CLP",contactPhone:"+56 9 1234 5678",contactEmail:"contacto@viajapro.cl",paymentMethods:["Webpay","Mercado Pago","Transferencia","Efectivo"],emailEndpoint:""};
function initData(){if(!localStorage.getItem("vp_trips"))localStorage.setItem("vp_trips",JSON.stringify(DEFAULT_TRIPS));if(!localStorage.getItem("vp_events"))localStorage.setItem("vp_events",JSON.stringify(DEFAULT_EVENTS));if(!localStorage.getItem("vp_bookings"))localStorage.setItem("vp_bookings","[]");if(!localStorage.getItem("vp_settings"))localStorage.setItem("vp_settings",JSON.stringify(DEFAULT_SETTINGS));}
initData();
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const getTrips=()=>JSON.parse(localStorage.getItem("vp_trips")||"[]"),getEvents=()=>JSON.parse(localStorage.getItem("vp_events")||"[]"),getBookings=()=>JSON.parse(localStorage.getItem("vp_bookings")||"[]"),getSettings=()=>({...DEFAULT_SETTINGS,...JSON.parse(localStorage.getItem("vp_settings")||"{}")});
const money=v=>new Intl.NumberFormat("es-CL",{style:"currency",currency:getSettings().currency||"CLP",maximumFractionDigits:0}).format(v);
const fmtDate=d=>new Date(d+"T12:00:00").toLocaleDateString("es-CL",{weekday:"short",day:"2-digit",month:"short",year:"numeric"});
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
let currentItem=null,currentType="trip",selectedSeats=[],ticketQty=1,lastPurchase=null;
function activeBookings(){return getBookings().filter(b=>b.status!=="Cancelada");}
function occupiedForTrip(id){return activeBookings().filter(b=>b.type==="trip"&&b.itemId===id).flatMap(b=>b.seats||[]);}
function soldForEvent(id){return activeBookings().filter(b=>b.type==="event"&&b.itemId===id).reduce((n,b)=>n+(b.quantity||1),0);}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),3000);}
function renderAll(q="",date=""){renderTrips(q,date);renderEvents(q,date);}
function renderTrips(q="",date=""){
 const trips=getTrips().filter(t=>t.status==="Activo"&&(!q||`${t.destination} ${t.origin}`.toLowerCase().includes(q.toLowerCase()))&&(!date||t.date===date));
 $("#tripGrid").innerHTML="";$("#tripCount").textContent=`${trips.length} ${trips.length===1?"viaje":"viajes"}`;$("#emptyTrips").classList.toggle("hidden",trips.length>0);
 trips.forEach(t=>{const available=Math.max(0,t.seats-occupiedForTrip(t.id).length),percent=t.seats?available/t.seats*100:0;const card=document.createElement("article");card.className="trip-card";card.innerHTML=`<div class="trip-image" style="background-image:url('${esc(t.image)}')"><span class="trip-badge">${available?"Disponible":"Agotado"}</span></div><div class="trip-body"><div class="trip-route"><div><h3>${esc(t.destination)}</h3><p>Desde ${esc(t.origin)}</p></div><div class="trip-price"><strong>${money(t.price)}</strong><small>por persona</small></div></div><p class="muted">${esc(t.description||"")}</p><div class="trip-meta"><div class="meta-item">📅 Fecha<strong>${fmtDate(t.date)}</strong></div><div class="meta-item">🕒 Salida<strong>${esc(t.time)} hrs</strong></div></div><div class="availability"><span style="width:${percent}%"></span></div><div class="availability-text"><span>${available} disponibles</span><span>${t.seats} asientos</span></div><button class="primary-btn full" ${available?"":"disabled"} data-buy-trip="${t.id}">${available?"Comprar pasaje":"Sin disponibilidad"}</button></div>`;$("#tripGrid").appendChild(card);});
 $$('[data-buy-trip]').forEach(b=>b.onclick=()=>openPurchase("trip",b.dataset.buyTrip));
}
function renderEvents(q="",date=""){
 const events=getEvents().filter(e=>e.status==="Activo"&&(!q||`${e.name} ${e.venue}`.toLowerCase().includes(q.toLowerCase()))&&(!date||e.date===date));
 $("#eventGrid").innerHTML="";$("#eventCount").textContent=`${events.length} ${events.length===1?"evento":"eventos"}`;$("#emptyEvents").classList.toggle("hidden",events.length>0);
 events.forEach(e=>{const available=Math.max(0,e.capacity-soldForEvent(e.id)),percent=e.capacity?available/e.capacity*100:0;const card=document.createElement("article");card.className="trip-card";card.innerHTML=`<div class="trip-image" style="background-image:url('${esc(e.image)}')"><span class="trip-badge">${available?"Entradas disponibles":"Agotado"}</span></div><div class="trip-body"><div class="trip-route"><div><h3>${esc(e.name)}</h3><p>${esc(e.venue)}</p></div><div class="trip-price"><strong>${money(e.price)}</strong><small>por entrada</small></div></div><p class="muted">${esc(e.description||"")}</p><div class="trip-meta"><div class="meta-item">📅 Fecha<strong>${fmtDate(e.date)}</strong></div><div class="meta-item">🕒 Inicio<strong>${esc(e.time)} hrs</strong></div></div><div class="availability"><span style="width:${percent}%"></span></div><div class="availability-text"><span>${available} disponibles</span><span>${e.capacity} capacidad</span></div><button class="primary-btn full" ${available?"":"disabled"} data-buy-event="${e.id}">${available?"Comprar entrada":"Agotado"}</button></div>`;$("#eventGrid").appendChild(card);});
 $$('[data-buy-event]').forEach(b=>b.onclick=()=>openPurchase("event",b.dataset.buyEvent));
}
function renderPaymentOptions(){const methods=getSettings().paymentMethods||DEFAULT_SETTINGS.paymentMethods;$("#paymentOptions").innerHTML=methods.map((m,i)=>`<label class="payment-option"><input type="radio" name="paymentMethod" value="${esc(m)}" ${i===0?"checked":""}><span>${m==="Webpay"?"💳":m==="Mercado Pago"?"📱":m==="Transferencia"?"🏦":"💵"}</span><strong>${esc(m)}</strong></label>`).join("");$$('input[name="paymentMethod"]').forEach(r=>r.onchange=updatePaymentNote);updatePaymentNote();}
function updatePaymentNote(){const method=$('input[name="paymentMethod"]:checked')?.value||"";$("#paymentNote").textContent=method==="Transferencia"?"La compra quedará registrada como pagada en esta versión demo. En producción debe verificarse la transferencia.":method==="Efectivo"?"La compra quedará pendiente de cobro presencial, pero el QR será generado.":"Pago simulado para pruebas. La pasarela real debe conectarse mediante servidor seguro.";}
function openPurchase(type,id){currentType=type;currentItem=(type==="trip"?getTrips():getEvents()).find(x=>x.id===id);selectedSeats=[];ticketQty=1;$("#purchaseForm").reset();$("#attendeesSection").classList.add("hidden");$("#attendeesFields").innerHTML="";
 if(type==="trip"){$("#modalItemSummary").innerHTML=`<span class="eyebrow dark">Compra de pasaje</span><h2>${esc(currentItem.origin)} → ${esc(currentItem.destination)}</h2><p class="muted">${fmtDate(currentItem.date)} · ${esc(currentItem.time)} hrs · ${money(currentItem.price)} por persona</p>`;$("#seatSection").classList.remove("hidden");$("#ticketSection").classList.add("hidden");$("#quantityLabel").textContent="Asientos";renderSeats();}
 else{$("#modalItemSummary").innerHTML=`<span class="eyebrow dark">Compra de entrada</span><h2>${esc(currentItem.name)}</h2><p class="muted">${esc(currentItem.venue)} · ${fmtDate(currentItem.date)} · ${esc(currentItem.time)} hrs · ${money(currentItem.price)} por entrada</p>`;$("#seatSection").classList.add("hidden");$("#ticketSection").classList.remove("hidden");$("#quantityLabel").textContent="Entradas";updateTicketQty();}
 renderPaymentOptions();updateTotal();$("#purchaseModal").classList.remove("hidden");}
function renderSeats(){const occupied=occupiedForTrip(currentItem.id),map=$("#seatMap");map.innerHTML="";for(let i=1;i<=currentItem.seats;i++){const btn=document.createElement("button");btn.type="button";btn.className="seat-btn";btn.textContent=i;if(occupied.includes(i)){btn.classList.add("occupied");btn.disabled=true;}btn.onclick=()=>{selectedSeats.includes(i)?selectedSeats=selectedSeats.filter(x=>x!==i):selectedSeats.push(i);btn.classList.toggle("selected");updateTotal();renderAttendees();};map.appendChild(btn);}}
function updateTicketQty(){const available=Math.max(0,currentItem.capacity-soldForEvent(currentItem.id));ticketQty=Math.max(1,Math.min(ticketQty,Math.min(10,available)));$("#ticketQty").textContent=ticketQty;$("#ticketAvailability").textContent=`Disponibles: ${available}. Máximo 10 por compra.`;updateTotal();renderAttendees();}
$("#qtyMinus").onclick=()=>{if(ticketQty>1){ticketQty--;updateTicketQty();}};$("#qtyPlus").onclick=()=>{ticketQty++;updateTicketQty();};
function renderAttendees(){
 const section=$("#attendeesSection"),box=$("#attendeesFields");
 const units=currentType==="trip"?[...selectedSeats].sort((a,b)=>a-b):Array.from({length:ticketQty},(_,i)=>i+1);
 if(!units.length){section.classList.add("hidden");box.innerHTML="";return;}
 section.classList.remove("hidden");
 $("#attendeesTitle").textContent=currentType==="trip"?"Datos de pasajeros":"Datos de asistentes";
 $("#attendeesHelp").textContent=currentType==="trip"?"Cada pasajero quedará vinculado a su asiento.":"Cada asistente quedará vinculado a una entrada.";
 const previous={};$$('[data-attendee-index]').forEach(el=>{const i=el.dataset.attendeeIndex;previous[i]=previous[i]||{};previous[i][el.dataset.attendeeField]=el.value;});
 box.innerHTML=units.map((unit,i)=>`<div class="attendee-card"><h4>${i===0?(currentType==="trip"?"Pasajero principal":"Asistente principal"):(currentType==="trip"?`Pasajero ${i+1}`:`Asistente ${i+1}`)} <span class="attendee-tag">${currentType==="trip"?`Asiento ${unit}`:`Entrada ${unit}`}</span></h4>${i===0?'<p class="muted">Se usarán los datos del comprador.</p>':`<div class="attendee-grid"><div class="field"><label>Nombre completo</label><input required data-attendee-index="${i}" data-attendee-field="name" value="${esc(previous[i]?.name||'')}"></div><div class="field"><label>RUT / Documento</label><input required data-attendee-index="${i}" data-attendee-field="document" value="${esc(previous[i]?.document||'')}"></div></div>`}</div>`).join("");
}
function collectAttendees(){
 const buyerName=$("#buyerName").value.trim(),buyerDoc=$("#buyerId").value.trim();
 const units=currentType==="trip"?[...selectedSeats].sort((a,b)=>a-b):Array.from({length:ticketQty},(_,i)=>i+1);
 return units.map((unit,i)=>({name:i===0?buyerName:document.querySelector(`[data-attendee-index="${i}"][data-attendee-field="name"]`)?.value.trim()||"",document:i===0?buyerDoc:document.querySelector(`[data-attendee-index="${i}"][data-attendee-field="document"]`)?.value.trim()||"",seat:currentType==="trip"?unit:null,ticket:currentType==="event"?unit:null,checkedIn:false,checkedInAt:null}));
}
function attendeesText(b){return (b.attendees||[]).map(a=>b.type==="trip"?`${a.name} (asiento ${a.seat})`:`${a.name} (entrada ${a.ticket})`).join(", ");}
function updateTotal(){if(!currentItem)return;if(currentType==="trip"){selectedSeats.sort((a,b)=>a-b);$("#selectedLabel").textContent=selectedSeats.length?selectedSeats.join(", "):"Ninguno";$("#purchaseTotal").textContent=money(currentItem.price*selectedSeats.length);}else{$("#selectedLabel").textContent=String(ticketQty);$("#purchaseTotal").textContent=money(currentItem.price*ticketQty);}}
function qrPayload(b,a){return JSON.stringify({system:"ViajaPro",code:b.code,personCode:a?.qrCode||b.code,type:b.type,itemId:b.itemId,token:a?.qrToken||b.qrToken});}
function ensureIndividualQrs(attendees,code){return attendees.map((a,i)=>({...a,qrCode:a.qrCode||`${code}-${String(i+1).padStart(2,"0")}`,qrToken:a.qrToken||(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)),checkedIn:!!a.checkedIn,checkedInAt:a.checkedInAt||null,checkedInBy:a.checkedInBy||null}));}
async function sendReceipt(b,automatic=false){const settings=getSettings();const item=b.type==="trip"?getTrips().find(x=>x.id===b.itemId):getEvents().find(x=>x.id===b.itemId);const subject=encodeURIComponent(`Comprobante ${b.code} - ${settings.companyName}`);const body=encodeURIComponent(`Hola ${b.passenger},\n\nTu compra fue registrada.\nCódigo: ${b.code}\nTipo: ${b.type==="trip"?"Pasaje":"Entrada"}\nDetalle: ${b.type==="trip"?`${item?.origin} a ${item?.destination}`:item?.name}\nFecha: ${item?.date} ${item?.time}\nCantidad/Asientos: ${b.type==="trip"?(b.seats||[]).join(", "):b.quantity}\nPersonas: ${attendeesText(b)||b.passenger}\nTotal: ${money(b.total)}\nMedio de pago: ${b.paymentMethod}\nEstado: ${b.status}\n\nPresenta el código QR al ingresar.`);
 if(settings.emailEndpoint){try{const res=await fetch(settings.emailEndpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({to:b.email,subject:`Comprobante ${b.code}`,purchase:b,qrData:(b.attendees||[]).map(a=>({person:a.name,code:a.qrCode,data:qrPayload(b,a)}))})});if(!res.ok)throw new Error();toast("Comprobante enviado al correo");return;}catch{toast("No se pudo conectar con el servicio de correo");}}
 if(automatic){toast("Compra registrada. Configura el servicio de correo para envío automático real.");return;}
 location.href=`mailto:${encodeURIComponent(b.email)}?subject=${subject}&body=${body}`;
}
$("#purchaseForm").addEventListener("submit",e=>{e.preventDefault();if(currentType==="trip"&&!selectedSeats.length){toast("Selecciona al menos un asiento");return;}const bookings=getBookings(),code="VP-"+Math.floor(100000+Math.random()*900000),method=$('input[name="paymentMethod"]:checked')?.value||"No informado";const attendees=collectAttendees();if(attendees.some(a=>!a.name||!a.document)){toast("Completa los datos de todas las personas");return;}const individualAttendees=ensureIndividualQrs(attendees,code);const b={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(),code,type:currentType,itemId:currentItem.id,passenger:$("#buyerName").value.trim(),document:$("#buyerId").value.trim(),phone:$("#buyerPhone").value.trim(),email:$("#buyerEmail").value.trim(),attendees:individualAttendees,seats:currentType==="trip"?[...selectedSeats]:[],quantity:currentType==="event"?ticketQty:selectedSeats.length,total:currentItem.price*(currentType==="trip"?selectedSeats.length:ticketQty),paymentMethod:method,paymentStatus:method==="Efectivo"?"Pendiente":"Pagado",createdAt:new Date().toISOString(),status:"Confirmada",checkedIn:false,checkedInAt:null,qrToken:(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2))};bookings.push(b);localStorage.setItem("vp_bookings",JSON.stringify(bookings));lastPurchase=b;$("#purchaseModal").classList.add("hidden");showSuccess(b);renderAll();sendReceipt(b,true);});
function showSuccess(b){$("#successText").textContent=`Compra ${b.code}. Se generó un QR individual para cada persona. Cada QR registra solamente a su titular.`;const box=$("#successQr");box.innerHTML="";box.classList.add("individual-qr-grid");(b.attendees||[]).forEach(a=>{const card=document.createElement("div");card.className="individual-qr-card";card.innerHTML=`<h4>${esc(a.name)}</h4><p>${b.type==="trip"?`Asiento ${a.seat}`:`Entrada ${a.ticket}`}</p><div class="individual-qr-image"></div><small>${esc(a.qrCode)}</small>`;box.appendChild(card);const q=card.querySelector(".individual-qr-image");if(window.QRCode)new QRCode(q,{text:qrPayload(b,a),width:180,height:180,correctLevel:QRCode.CorrectLevel.H});else q.textContent=a.qrCode;});$("#successModal").classList.remove("hidden");}
$("#downloadQrBtn").onclick=()=>{const cards=[...document.querySelectorAll("#successQr .individual-qr-card")];if(!cards.length){toast("Los QR aún no están listos");return;}cards.forEach((card,i)=>setTimeout(()=>{const img=card.querySelector("img"),canvas=card.querySelector("canvas"),url=img?.src||canvas?.toDataURL("image/png");if(!url)return;const a=document.createElement("a");a.href=url;a.download=`QR-${lastPurchase?.attendees?.[i]?.qrCode||i+1}.png`;a.click();},i*250));};
$("#emailReceiptBtn").onclick=()=>lastPurchase&&sendReceipt(lastPurchase);
function contactAdmin(b){const st=getSettings(),item=b?.type==="trip"?getTrips().find(x=>x.id===b.itemId):getEvents().find(x=>x.id===b.itemId),detail=b?(b.type==="trip"?`${item?.origin||""} a ${item?.destination||""}`:item?.name||""):"mi compra";const subject=encodeURIComponent(`Solicitud sobre compra ${b?.code||""}`),body=encodeURIComponent(`Hola, necesito ayuda con ${detail}.\nCódigo de compra: ${b?.code||""}\nNombre: ${b?.passenger||""}\nMotivo: `);location.href=`mailto:${encodeURIComponent(st.contactEmail)}?subject=${subject}&body=${body}`;}
$("#contactAdminBtn").onclick=()=>lastPurchase&&contactAdmin(lastPurchase);
$("#lookupBtn").onclick=()=>{const code=$("#bookingCode").value.trim().toUpperCase(),b=getBookings().find(x=>x.code.toUpperCase()===code),out=$("#bookingResult");if(!b){out.innerHTML=`<div class="booking-card"><strong>No encontramos esa compra.</strong><p class="muted">Revisa el código e intenta nuevamente.</p></div>`;return;}const item=b.type==="trip"?getTrips().find(x=>x.id===b.itemId):getEvents().find(x=>x.id===b.itemId);out.innerHTML=`<div class="booking-card"><div class="booking-card-head"><div><span class="eyebrow dark">${esc(b.code)}</span><h3>${b.type==="trip"?`${esc(item?.origin||"-")} → ${esc(item?.destination||"-")}`:esc(item?.name||"Evento")}</h3></div><span class="status ${b.status==="Cancelada"?"cancelled":b.checkedIn?"finished":"confirmed"}">${b.status==="Cancelada"?"Cancelada":b.checkedIn?"Registrada":"Válida"}</span></div><p><strong>Comprador:</strong> ${esc(b.passenger)}</p><p><strong>Fecha:</strong> ${item?fmtDate(item.date):"-"} · ${esc(item?.time||"-")}</p><p><strong>${b.type==="trip"?"Asientos":"Entradas"}:</strong> ${b.type==="trip"?(b.seats||[]).join(", "):b.quantity}</p>${b.attendees?.length?`<div class="cancel-info"><strong>Personas registradas</strong><br>${b.attendees.map(a=>`${a.checkedIn?"✅":"⬜"} ${esc(a.name)} · ${b.type==="trip"?`Asiento ${a.seat}`:`Entrada ${a.ticket}`} · QR ${esc(a.qrCode||b.code)}`).join("<br>")}</div>`:""}<p><strong>Pago:</strong> ${esc(b.paymentMethod)} · ${esc(b.paymentStatus)}</p><p><strong>Total:</strong> ${money(b.total)}</p>${b.status==="Cancelada"?`<div class="cancel-info"><strong>Compra cancelada</strong><br>${esc(b.cancelReason||"Sin motivo informado")}<br>Devolución: ${money(b.refundAmount||0)} · ${esc(b.refundMethod||"No informada")}</div>`:""}<div class="contact-actions"><button class="secondary-btn" onclick="contactAdminById('${b.id}')">Solicitar cancelación o ayuda</button></div></div>`;};
$$('[data-close-modal]').forEach(x=>x.onclick=()=>$("#purchaseModal").classList.add("hidden"));$$('[data-close-success]').forEach(x=>x.onclick=()=>$("#successModal").classList.add("hidden"));$("#menuBtn").onclick=()=>document.querySelector(".topbar nav").classList.toggle("open");renderAll();

window.contactAdminById=id=>{const b=getBookings().find(x=>x.id===id);if(b)contactAdmin(b);};
function renderPublicContact(){const st=getSettings(),el=$("#publicContact");if(!el)return;const digits=(st.contactPhone||"").replace(/\D/g,"");el.innerHTML=`<a class="contact-link" href="mailto:${esc(st.contactEmail)}">✉ ${esc(st.contactEmail)}</a>${digits?`<a class="contact-link whatsapp" target="_blank" rel="noopener" href="https://wa.me/${digits}">WhatsApp</a>`:""}`;}
renderPublicContact();
