const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const trips=()=>read('vp_trips'),events=()=>read('vp_events'),bookings=()=>read('vp_bookings');const people=b=>(b.attendees?.length?b.attendees:[{name:b.passenger,document:b.document,seat:(b.seats||[])[0],ticket:1}]);const peopleHtml=b=>people(b).map(a=>`${esc(a.name)} · ${b.type==='trip'?`Asiento ${a.seat}`:`Entrada ${a.ticket}`}`).join('<br>');function toast(m){const t=$('#toast');t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2200)}function item(b){const x=b.type==='trip'?trips().find(v=>v.id===b.itemId):events().find(v=>v.id===b.itemId);return b.type==='trip'?(x?`${x.origin} → ${x.destination} · ${x.date} ${x.time}`:'Viaje eliminado'):(x?`${x.name} · ${x.venue} · ${x.date} ${x.time}`:'Evento eliminado')}
$('#workerLoginForm').onsubmit=e=>{e.preventDefault();if($('#workerUser').value==='trabajador'&&$('#workerPassword').value==='1234'){sessionStorage.setItem('vp_worker','1');show()}else toast('Datos incorrectos')};function show(){$('#workerLogin').classList.add('hidden');$('#workerApp').classList.remove('hidden');renderRecords();initScanner()}if(sessionStorage.getItem('vp_worker')==='1')show();$('#workerLogout').onclick=()=>{sessionStorage.removeItem('vp_worker');location.reload()};
$$('.worker-tab').forEach(b=>b.onclick=()=>{$$('.worker-tab').forEach(x=>x.classList.toggle('active',x===b));$$('.worker-view').forEach(x=>x.classList.add('hidden'));$('#worker'+b.dataset.workerView[0].toUpperCase()+b.dataset.workerView.slice(1)).classList.remove('hidden');renderRecords()});
function parse(raw){try{const o=JSON.parse(raw);return {purchaseCode:o.code||'',personCode:o.personCode||o.attendeeCode||o.code||''}}catch{const x=String(raw||'').trim();return {purchaseCode:x,personCode:x}}}
let scanLocked=false,feedbackTimer=null;
function showScanFeedback(ok,title,detail=''){
  let box=$('#qrAutoFeedback');
  if(!box){box=document.createElement('div');box.id='qrAutoFeedback';box.className='qr-auto-feedback hidden';document.body.appendChild(box)}
  box.className=`qr-auto-feedback ${ok?'ok':'bad'}`;
  box.innerHTML=`<div class="qr-auto-symbol">${ok?'✓':'✕'}</div><h2>${esc(title)}</h2>${detail?`<p>${esc(detail)}</p>`:''}`;
  clearTimeout(feedbackTimer);
  feedbackTimer=setTimeout(()=>{box.classList.add('hidden');scanLocked=false;$('#workerScanResult').innerHTML='<div class="empty-icon">▣</div><p>Escanea un código.</p>'},2000);
}
function normalizePeople(b){if(!b.attendees?.length)b.attendees=people(b).map((a,i)=>({...a,qrCode:`${b.code}-${String(i+1).padStart(2,'0')}`,checkedIn:!!b.checkedIn,checkedInAt:b.checkedInAt||null,checkedInBy:b.checkedInBy||null}));return b.attendees}
function validate(raw){
  if(scanLocked)return;scanLocked=true;
  const parsed=parse(raw),purchase=parsed.purchaseCode.toUpperCase(),person=parsed.personCode.toUpperCase(),l=bookings();
  let i=l.findIndex(x=>x.code.toUpperCase()===purchase||normalizePeople(x).some(a=>(a.qrCode||'').toUpperCase()===person));const out=$('#workerScanResult');
  if(i<0){out.innerHTML='<div class="scan-bad">✕</div><h3>QR no válido</h3><p>No existe.</p>';showScanFeedback(false,'QR no válido','Código inexistente');return}
  const b=l[i],kind=b.type==='trip'?'Pasaje':'Entrada',ps=normalizePeople(b);let ai=ps.findIndex(a=>(a.qrCode||'').toUpperCase()===person);if(ai<0&&person===b.code.toUpperCase())ai=0;
  if(ai<0){showScanFeedback(false,'QR no válido','No corresponde a una persona registrada');return}
  const a=ps[ai];
  if(b.status==='Cancelada'||b.paymentStatus==='Reembolsado'){out.innerHTML=`<div class="scan-bad">✕</div><h3>No autorizado</h3><p>${esc(item(b))}</p>`;showScanFeedback(false,'QR no válido',`${kind} cancelado o reembolsado`);return}
  if(a.checkedIn){out.innerHTML=`<div class="scan-bad">✕</div><h3>Ya registrado</h3><p>${esc(a.name)}</p>`;showScanFeedback(false,'QR ya utilizado',`${a.name} ya fue registrado`);return}
  const now=new Date().toISOString();ps[ai]={...a,checkedIn:true,checkedInAt:now,checkedInBy:'trabajador'};b.attendees=ps;b.checkedIn=ps.every(x=>x.checkedIn);b.checkedInAt=b.checkedIn?now:null;b.checkedInBy=b.checkedIn?'trabajador':null;write('vp_bookings',l);
  out.innerHTML=`<div class="scan-good">✓</div><h3>${kind} registrado</h3><p><strong>${esc(a.name)}</strong><br>${b.type==='trip'?`Asiento ${a.seat}`:`Entrada ${a.ticket}`}<br>${esc(item(b))}</p>`;
  renderRecords();showScanFeedback(true,`${kind} válido`,a.name);
}
$('#workerValidateBtn').onclick=()=>validate($('#workerManualQr').value);
let started=false;function initScanner(){if(started||!window.Html5QrcodeScanner)return;started=true;new Html5QrcodeScanner('workerQrReader',{fps:10,qrbox:{width:230,height:230}},false).render(t=>validate(t),()=>{})}
function renderRecords(){const ts=trips(),es=events(),all=bookings();const tf=$('#tripRecordFilter'),ef=$('#eventRecordFilter');const tv=tf.value,ev=ef.value;tf.innerHTML='<option value="">Todos los viajes</option>'+ts.map(x=>`<option value="${x.id}">${esc(x.origin)} → ${esc(x.destination)} · ${x.date}</option>`).join('');ef.innerHTML='<option value="">Todos los eventos</option>'+es.map(x=>`<option value="${x.id}">${esc(x.name)} · ${x.date}</option>`).join('');tf.value=tv;ef.value=ev;const tq=$('#tripRecordSearch').value.toLowerCase(),eq=$('#eventRecordSearch').value.toLowerCase();const rows=all.flatMap(b=>normalizePeople(b).filter(a=>a.checkedIn).map(a=>({b,a})));const tb=rows.filter(({b,a})=>b.type==='trip'&&(!tf.value||b.itemId===tf.value)&&(!tq||b.code.toLowerCase().includes(tq)||a.name.toLowerCase().includes(tq)));const eb=rows.filter(({b,a})=>b.type==='event'&&(!ef.value||b.itemId===ef.value)&&(!eq||b.code.toLowerCase().includes(eq)||a.name.toLowerCase().includes(eq)));$('#tripRecordsTable').innerHTML=tb.map(({b,a})=>`<tr><td>${esc(item(b))}</td><td><strong>${esc(a.qrCode||b.code)}</strong></td><td>${esc(a.name)}</td><td>${esc(a.seat)}</td><td>✓ ${new Date(a.checkedInAt).toLocaleString('es-CL')}</td></tr>`).join('')||'<tr><td colspan="5">No hay pasajes registrados.</td></tr>';$('#eventRecordsTable').innerHTML=eb.map(({b,a})=>`<tr><td>${esc(item(b))}</td><td><strong>${esc(a.qrCode||b.code)}</strong></td><td>${esc(a.name)}</td><td>${esc(a.ticket)}</td><td>✓ ${new Date(a.checkedInAt).toLocaleString('es-CL')}</td></tr>`).join('')||'<tr><td colspan="5">No hay entradas registradas.</td></tr>'}
$('#tripRecordFilter').onchange=renderRecords;$('#eventRecordFilter').onchange=renderRecords;$('#tripRecordSearch').oninput=renderRecords;$('#eventRecordSearch').oninput=renderRecords;
